- name: homebrew add repo
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew: update_homebrew=yes

# brew
- name: Install homebrew packages.
  homebrew: >
    name: ["{{ item.name | default(item) }}"]
    install_options: ["{{ item.install_options | default(omit) }}"]
    state: "{{ item.state | default(homebrew_default_state) }}"
  with_items: "{{ homebrew_packages }}"
- name: Create directory for packages info.
  file: path=brew_info state=directory
- name: Save brew info.
  shell: brew info "{{ item.name }}" > brew_info/{{ item.name }}
  with_items: "{{ homebrew_packages }}"

# cask
- name: Install cask packages.
  homebrew_cask:
    name: "{{ item.name }}" 
    state: "{{ item.state|default('present') }}"
  with_items: "{{ homebrew_cask_packages }}"
- name: cask mkdir for package info
  file: path=cask_info state=directory
- name: cask save info
  shell: brew cask info {{ item.name }} > cask_info/{{ item.name }}
  with_items: "{{ homebrew_cask_packages }}"
